[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "camels-sam"
authors = [{name = "Perez, L.A", email = "laperez5@asu.edu"}]
dynamic = ["version", "description"]
